# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install
      run: npm install
      
    - name: Test
      run: npm test
      
    # - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
      if: github.ref == 'ref/heads/master' && job.status == 'success' #only run when test is passed
      run:  |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/group4-weatherly-app.git
        git push heroku HEAD:master -f
      
